### PR TITLE
[WIP] Optimize transfers query

### PR DESCRIPTION
**Pull request by zhinfuhnya**

### CODE REVIEW

**Comment by aquabu** [comment]
Looks like there was a coverage drop. That said it seems like a large drop for this number of lines of code:
Screen Shot 2021-05-07 at 2 06 06 PM

I wonder if something changed in Rcov configuration.

**Review by aquabu — CHANGES_REQUESTED** [review]
@zhinfuhnya checking back on this. I think it just had a code coverage drop that needs to be resolved.

Or if it is still [WIP] please mark it as Draft. Thanks!

**Comment by aquabu** [comment]
@zhinfuhnya should we close this one? Seems like we may try to optimize this again later but we are paused for now.

**Comment by zhinfuhnya** [comment]
@aquabu I agree, we can close this PR

**Pull request closed without merging**
