### PR TITLE
Restyled Tabler bootstrap UI Kit

### PR DESCRIPTION
**Pull request by aquabu**

### CODE REVIEW

**Comment by aquabu** [comment]
@leedaniel2018 @wowcool nice work :)

For others who are reviewing you can view the UI Kit restyled tabler.io bootstrap them with
`open ./tabler/index.html `


# Minor Fixes

The collapsed nav should be a named menu item instead of only appearing when you click on the `cards menu` item
Screen Shot 2021-03-24 at 10 14 43 PM

Needs a a to show the collapsed blue navigation.

Should have menu items to show combinations of the blue far left nav or the white sub-nav on the left expanded / contracted. You can show this as separate menu items without the rest of the UI / Kit.

**Comment by aquabu** [comment]
@Alexey1100 & @Riddlerrr do you think we should move the tabler folder to the public directory to make it more accessible?

**Review by aquabu — COMMENTED** [review]
Left a couple minor requested changes.

**Comment by wowcool** [comment]
@aquabu Added page layouts.

**Comment by wowcool** [comment]
@aquabu Can you check latest with collapsing menu and let me know if this is ok. Thanks

**Comment by wowcool** [comment]
@aquabu 4/1 Figma Icon Update

**Comment by aquabu** [comment]
thanks @wowcool and @leedaniel2018

I merged this one.

Could you make a new PR to fix these minor issues?

## Alignment for the inputs tab is off
Screen Shot 2021-04-13 at 1 01 10 PM

## Main Nav Needs The Correct Icons

Far left "Token Admin" menu item 
Screen Shot 2021-04-13 at 1 00 52 PM

should use the new token Icon:
Screen Shot 2021-04-13 at 1 00 58 PM

The outer nav should look like this
Screen Shot 2021-04-13 at 1 08 38 PM

Should have a way to expand and contract the nav to show the expanded and contracted navigation for the outer and inner navigation.

**Comment by aquabu** [comment]
@wowcool @leedaniel2018 

The outer and inner nav is updated to have these states that you can find in Figma:

Снимок экрана 2021-04-01 в 23 49 51

Снимок экрана 2021-04-01 в 23 50 00

**Comment by aquabu** [comment]
You can re-open this branch with a new PR if that's easiest.

**Pull request merged**
