### PR TITLE
Disable Rspec retries in CI

### PR DESCRIPTION
**Pull request by Alexey1100**
Resolves:
https://www.pivotaltracker.com/story/show/178677287

### CODE REVIEW

**Comment by Alexey1100** [comment]
I've disabled test retry, trying to avoid simplecov issue, since the retry run probably overwrites the simplecov report for the full run, making it incomplete.

But looks like we have lots of flaky tests, related to API ids stubbing.

**Comment by aquabu** [comment]
good catch @Alexey1100

**Comment by Riddlerrr** [comment]
@Alexey1100 
As a workaround, what if we force disable `SIMPLECOV_ENABLED` for retry failures:
```
SIMPLECOV_ENABLED=false env bundle exec rspec --only-failures --format documentation
```

This way simplecov will not overwrite results on second rspec run.

**Comment by Alexey1100** [comment]
Resolved in #2233

**Pull request closed without merging**
