### PR TITLE
initial commit. added base tabler styles, moved current upside styles…

### PR DESCRIPTION
**Pull request by o-bahriy**
https://www.pivotaltracker.com/story/show/178124805

just to keep in mind

demo.css, upside.css, upside-vendors.css - tabler base from tabler.io
demo-current.css, upside-current.css, upside-vendors-current.css - version from acceptance branch(messed up one)
demo-override.css, upside-vendors-override.css and [wip] upside-override.css - new files which overrides behaviour from tabler base, based on current files(changes from current version, extracted into separate files)

this will be renamed into xxx-base.css, xxx-legacy.css, xxx.css bit later

### CODE REVIEW

**Comment by o-bahriy** [comment]
i kept names tabler.css, tabler-vendors.css, demo.css for tabler base styles
*-override - for changes
-current that files are present in acceptance branch now - can be deleted later after we will verify everything works as expected

some troubles with ranges present for now

**Comment by o-bahriy** [comment]
@aquabu @Alexey1100 @Riddlerrr i think before merge you can pull and check how it looks like(this is the default tabler styleguide copied to public folder)

**Comment by aquabu** [comment]
@o-bahriy **great work on this!!**

I found a few remaining issues...

## Images are broken in most places

For example they are missing on the Form Elements > Image Check section 
`/dev/styleguide/form-elements.html`

Screen Shot 2021-06-02 at 12 06 40 PM

## RTL Mode is broken

Screen Shot 2021-06-02 at 12 09 18 PM

## Documentation Link is broken

**Review by aquabu — CHANGES_REQUESTED** [review]
Need to fix missing images and other items from the main PR conversation tab.

**Pull request merged**
