### PR TITLE
Update transfer page table columns

### PR DESCRIPTION
**Pull request by zhinfuhnya**
https://www.pivotaltracker.com/n/projects/2167210/stories/177865235
https://www.pivotaltracker.com/n/projects/2167210/stories/178328783

Screen Shot 2021-05-24 at 10 26 27 PM

### CODE REVIEW

**Comment by zhinfuhnya** [comment]
After approve and merge close https://github.com/CoMakery/comakery-server/pull/2107

**Comment by Alexey1100** [comment]
Hmm haven't done the review yet, but looking at the attached screenshot I can see there's some issue.
Looks like the first transfer is paid, but PAY button is still there and there's no link to tx explorer.

Screenshot 2021-05-25 at 20 36 30

**Comment by Riddlerrr** [comment]
@zhinfuhnya Is this requirement done?

> - Include the blockchain address of the recipient in the "To" column. This is the users primary wallet address for the project token's blockchain network

I can't see any wallet address in the "To" column on the screenshot

**Comment by Alexey1100** [comment]
I think this PR https://github.com/CoMakery/comakery-server/pull/2131 includes that.
Maybe they should be merged in one, to avoid the confusion.

**Comment by zhinfuhnya** [comment]
@Alexey1100 I can't merge with PR #2131 because it has a lot of unnecessary things.

**Comment by aquabu** [comment]
This PR includes or replaces functionality from:
#2131 
#2107

Code is related to this working branch `feature/reorganize-transfer-page` and this PR that will not be merged #2137 

This is for these Pivotal tracker stories:
https://www.pivotaltracker.com/n/projects/2167210/stories/177865235
https://www.pivotaltracker.com/n/projects/2167210/stories/177867584
https://www.pivotaltracker.com/n/projects/2167210/stories/178234736

**Review by Alexey1100 — APPROVED** [review]

**Pull request merged**
