### PR TITLE
[#1791] Update wallets page

### PR DESCRIPTION
**Pull request by Lerek**

### CODE REVIEW

**Comment by aquabu** [comment]
@Lerek there is a merge conflict to resolve. I'm also reviewing.

**Review by aquabu — APPROVED** [review]

**Comment by aquabu** [comment]
@Lerek looks good to me other than the merge conflict. I'll also wait for 1 more review from @Alexey1100 or @Riddlerrr since it's a large PR.

**Comment by Riddlerrr** [comment]
I tried to use it a bit locally and found some issues:
1. I think we have to restrict to edit wallets with `source` is not "user_provided"
CoMakery - Achieve Big Missions 2021-01-13 10-18-29

2. When I click "edit" for BitcoinTest wallet the blockchain in the form is Bitcoin (not test):
CoMakery - Achieve Big Missions 2021-01-13 10-18-29

3. Editing to empty name just stuck:
CoMakery - Achieve Big Missions 2021-01-13 10-29-29

4. I think on adding wallet form some wallet name should be pre-populated by default:
image

5. No need to show "OPT-IN" button for opted in status.
CoMakery - Achieve Big Missions 2021-01-13 10-34-22

6. For the form above rename title to: "Opt-In to Algorand tokens". Because it's not only assets but apps too.

**Comment by aquabu** [comment]
@Riddlerrr great comments. Should any of these block this merge or is it ok to do these in a follow on commit?

My preference is to merge this PR and then improve it in follow ons.

**Comment by Lerek** [comment]
@aquabu i've adjusted comments :)

**Comment by Lerek** [comment]
@Riddlerrr would appreciate another CR :)

**Review by aquabu — APPROVED** [review]

**Pull request merged**
