### PR TITLE
Applied filter on chart on transfer page

### PR DESCRIPTION
**Pull request by shoaibmalik786**

### CODE REVIEW

**Comment by aquabu** [comment]
@shoaibmalik786 sorry the acceptance branch changed. Could you resolve the merge conflict. Thanks!

**Review by aquabu — CHANGES_REQUESTED** [review]
Please resolve the merge conflict. Thanks!

**Comment by shoaibmalik786** [comment]
> Please resolve the merge conflict. Thanks!

Done

**Review by aquabu — APPROVED** [review]

**Comment by aquabu** [comment]
@shoaibmalik786 thanks!

**Pull request merged**
