### PR TITLE
issue#1777 turn off discord/slack if not configured

### PR DESCRIPTION
**Pull request by matjacdev515**
#1777  enable/disable slack or discord buttons on signup/login according to env variables.

### CODE REVIEW

**Review by Riddlerrr — DISMISSED** [review]
The implementation looks good 👍 Well done!

But we have to add a few tests to cover the changes:
image

**Comment by Alexey1100** [comment]
Yep looks good :)

We will also need to delete these variables from `.env.required` file, since we have some logic around that (see `env_verifier.rb`)

**Comment by Alexey1100** [comment]
Also I believe, we have a Channels section in project settings (`/projects/:id/edit`) which tells you to sign in with Slack/Discord to be able to use it.
I think we want to adjust that as well.

**Review by Alexey1100 — APPROVED** [review]
👍

**Review by aquabu — APPROVED** [review]

**Comment by aquabu** [comment]
@Riddlerrr - @matjacdev515 fixed the test coverage issue you pointed out. I'm approving for merge.

**Review by Riddlerrr — APPROVED** [review]
👍

**Pull request merged**
