### PR TITLE
Transfers page: Change HTML structure to using bootstrap

### PR DESCRIPTION
**Pull request by Riddlerrr**
task: https://www.pivotaltracker.com/story/show/178457918

Fixed:
- WalletConnect and Metamask buttons are outside of the page
- Create a new transfer button is at the top of the page

Some elements not perfectly aligned for now but we can fix it in further PR. It should require only css changes.

[Pretty looking diff](https://github.com/CoMakery/comakery-server/pull/2177/files?diff=split&w=1)

CoMakery - Achieve Big Missions 2021-06-10 12-17-47
CoMakery - Achieve Big Missions 2021-06-10 14-09-12
CoMakery - Achieve Big Missions 2021-06-10 12-52-50

### CODE REVIEW

**Comment by Riddlerrr** [comment]
@Alexey1100 @zhinfuhnya @aquabu The PR is finished and ready to review

**Comment by zhinfuhnya** [comment]
@Riddlerrr looks great to me except for the wallet connect button group:

Screen Shot 2021-06-10 at 1 36 54 PM

on the transfers page it should be aligned with the top group of buttons, like:
https://user-images.githubusercontent.com/81186018/120828526-4d0d0600-c565-11eb-92e6-c410b371f1f3.png
https://user-images.githubusercontent.com/81186018/120828681-7af24a80-c565-11eb-91a5-d02adb2a93db.png

on the accounts page, the wallet connect button group has moved to the right:

Screen Shot 2021-06-10 at 1 37 54 PM

**Comment by Riddlerrr** [comment]
@zhinfuhnya  Hmm, for accounts page for me it looks different:
CoMakery - Achieve Big Missions 2021-06-10 13-52-55

I'll try to fix wallet connect buttons alignment.

**Comment by Riddlerrr** [comment]
@zhinfuhnya Fixed the align of wallet connect buttons:
CoMakery - Achieve Big Missions 2021-06-10 14-09-12

**Review by aquabu — APPROVED** [review]

**Pull request merged**
